# Generated by Django 6.0.2 on 2026-05-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussines_name', models.CharField(max_length=100, verbose_name='Nombre del negocio')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de contacto')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
