# Generated by Django 6.0.2 on 2026-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
                ('bussines_name', models.CharField(max_length=20, verbose_name='Razon Social')),
                ('contact_name', models.CharField(max_length=30, verbose_name='Nombre de Contacto')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
