# Generated by Django 6.0.2 on 2026-05-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='bussines_name',
            new_name='business_name',
        ),
    ]
