# Generated by Django 6.0.2 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_bussines_name_supplier_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(max_length=100, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(max_length=80, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
