# Generated by Django 6.0.2 on 2026-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion'),
        ),
    ]
