# Generated by Django 6.0.2 on 2026-04-21 02:50

from django.db import migrations, models


def migrate_promo_categories_to_product(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(type='PROMO').update(type='PRODUCT')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_deleted_date_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_promo_categories_to_product,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('RAW_MATERIAL', 'Raw Material')], default='PRODUCT', max_length=20, verbose_name='Tipo'),
        ),
    ]
