# Generated by Django 6.0.2 on 2026-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('time', models.TimeField()),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10, verbose_name='Accion')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('area', models.CharField(choices=[('CAJA', 'Cashier'), ('COCINA', 'Kitchen'), ('ADMINISTRATION', 'Administration')], default='CAJA', max_length=15, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
    ]
