# Generated by Django 6.0.2 on 2026-05-02 03:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('unit_type', models.CharField(choices=[('MASS', 'Masa'), ('COUNT', 'Conteo')], default='MASS', max_length=10, verbose_name='Tipo de unidad')),
                ('factor_to_base', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Factor de conversion')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('stock', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock')),
                ('min_stock', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock minimo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='products.category', verbose_name='Categoria')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='inventory.measureunit', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
            },
        ),
    ]
