# Generated by Django 6.0.2 on 2026-06-14 20:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0009_remove_order_client_name'),
        ('purchases', '0004_purchase_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE_CONSUMPTION', 'Consumo por Venta'), ('WASTE', 'Merma'), ('ADJUSTMENT_IN', 'Ajuste de Entrada'), ('ADJUSTMENT_OUT', 'Ajuste de Salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Razón / Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order', verbose_name='Orden asociada')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='purchases.purchase', verbose_name='Compra asociada')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.rawmaterial', verbose_name='Materia prima')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
