# Generated by Django 6.0.2 on 2026-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='user',
        ),
    ]
