# Generated by Django 6.0.2 on 2026-04-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('order_number', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Numero de orden')),
                ('client_name', models.CharField(default='', max_length=50, verbose_name='Nombre del Cliente')),
                ('type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway')], default='DINE_IN', max_length=15, verbose_name='Tipo de la orden')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de reserva')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready')], default='PENDING', max_length=15, verbose_name='Estado de la orden')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de orden lista')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Productos de la Orden',
                'verbose_name_plural': 'Productos de las Ordenes',
            },
        ),
    ]
