# Generated by Django 6.0.2 on 2026-04-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_deleted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de eliminacion')),
                ('client_phone', models.CharField(max_length=10, verbose_name='Numero del Cliente')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('reference_note', models.TextField(verbose_name='Nota de referencia')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de Envio',
                'verbose_name_plural': 'Detalles de Envios',
            },
        ),
    ]
