# Generated by Django 6.0.2 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_deliverydetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("DINE_IN", "Dine In"),
                    ("TAKEAWAY", "Takeaway"),
                    ("DELIVERY", "Delivery"),
                ],
                default="DINE_IN",
                max_length=15,
                verbose_name="Tipo de la orden",
            ),
        ),
    ]
