# Generated by Django 6.0.2 on 2026-05-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_populate_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
    ]
